alias h='history'
alias ll='ls -la'
alias ws='cd $WORKSPACE'
alias tstr='date +%Y-%m-%d.%H%M%S'
alias dstr='date +%Y-%m-%d'
alias mvnst='mvn -DskipTests'
alias findsrc='find . ! -path "*/.git/*" ! -path "*/target/*" -type f'
